### ISSUE TITLE
Inconsistencies with Webapp and html file in releases

### ISSUE THREAD

**Issue by johnwuelk** [melaku-z/ethio-european-date-converter#347]
In the current releases dateconverter.html is faulty whereas the Webapp ethiopian-calendar.netlify.app is correct.

In dateconverter.html for example 25/07/2005 (Ge'ez/Amharic) should convert to April 3, 2013 but it converts to April 4. Can this be corrected?

**Comment by melaku-z** [comment]
Sure @johnwuelk . Can you try the latest release at [v4.0.1](https://github.com/melaku-z/ethio-european-date-converter/releases/tag/v4.0.1)? 
In the older release that contains dateconverter.html, there must have been timezone issue resulting in the error.
