### ISSUE TITLE
spelling error it should be "Saturday" insted of "Saterday"

### ISSUE THREAD

**Issue by johnhailu** [melaku-z/ethio-european-date-converter#430]
https://github.com/melaku-z/ethio-european-date-converter/blob/f494f10c8584e3b04815fb9cba61d0a7123fb661/packages/ethiopian-calendar-date-converter/src/ethiopianCalendarDateConverter.ts#L19

**Comment by melaku-z** [comment]
Thank you @johnhailu. Fixed in the latest version 4.2.2.
